http:
  middlewares:
    https-redirect:
      redirectScheme:
        scheme: https
        permanent: true
tls:
  certificates:
    - certFile: "/etc/certs/local-cert.pem"
      keyFile: "/etc/certs/local-key.pem"